---
version: '3'
services:
  stream-web:
    build: .
    restart: "always"
    ports:
      - "5000:5000"
    command: "python3 app.py"
    links:
      - "redis:redis"
  stream-buffer:
    build: .
    command: "python3 webcam.py"
    restart: "always"
    links:
      - "redis:redis"
    environment:
      - IP_CAMERA=${IP_CAMERA}
  redis:
    image: redis
