---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection
  labels:
    app: detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detection
  template:
    metadata:
      labels:
        app: detection
    spec:
      containers:
      - name: detection
        image: gvancuts/streamapp:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: detection
  labels:
    run: detection
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30600
  selector:
    app: detection
  type: NodePort
