---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  ports:
  - name: hub
    port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  selector:
    app: docker-registry
  type: NodePort
