---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcam-file
  labels:
    app: webcam-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcam-file
  template:
    metadata:
      labels:
        app: webcam-file
    spec:
      containers:
      - name: webcam-file
        image: localhost:30500/streamapp-file:latest
        imagePullPolicy: Always
        command: ["/usr/bin/python3", "webcam-file.py"]
        env:
          - name: IP_CAMERA
            value: 192.168.1.138

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    run: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
